### ISSUE TITLE
Image is fails to work with new Docker networking

### ISSUE THREAD

**Issue by kop** [janeczku/docker-alpine-kubernetes#6]
Hi.

I'm trying to use this image with new Docker Compose v2 format. I have only one network and `docker-compose.yml` looks as simple as:

```
version: '2'

volumes:
  redis_data:
    driver: local

services:

  # My app (built from alpine-kubenetes)
  worker:
    build: ./worker
    volumes:
      - ./worker:/srv/worker
    links:
      - redis

  # Redis
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
```

Node.js app deployed inside the `worker` container is not able to resolve `redis` hostname.
Same setup with stock Alpine image works just fine.

**Comment by janeczku** [comment]
Thanks for the report. Haven't made the switch yet to Compose v2. In the subject you mention docker networking yet in the compose file i see no settings related to networking. Could you paste the `docker logs` output for the worker container? Any maybe the content of /etc/hosts if that's feasible?

**Comment by janeczku** [comment]
To find out why the linked container does not resolve, it might help to add `DNSMASQ_VERBOSE` environment variable in the worker declaration:

```
  worker:
    build: ./worker
    volumes:
      - ./worker:/srv/worker
    links:
      - redis
    environment:
      - DNSMASQ_VERBOSE: 'true'
```

**Comment by kop** [comment]
> In the subject you mention docker networking yet in the compose file I see no settings related to networking

In Compose v2, if networking section is skipped it means that default bridge network called `<projectName>_default` is created and all containers are connected to this network.

> Sure here is the output of worker container

```
worker_1          | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
worker_1          | [s6-init] ensuring user provided files have correct perms...exited 0.
worker_1          | [fix-attrs.d] applying ownership & permissions fixes...
worker_1          | [fix-attrs.d] done.
worker_1          | [cont-init.d] executing container initialization scripts...
worker_1          | [cont-init.d] done.
worker_1          | [services.d] starting services
worker_1          | [Alpine-Kubernetes] Changed nameserver to 127.0.0.1
worker_1          | [services.d] done.
worker_1          | > worker@ watch /srv/worker
worker_1          | > nodemon worker.js
worker_1          | [nodemon] 1.9.1
worker_1          | [nodemon] to restart at any time, enter `rs`
worker_1          | [nodemon] watching: *.*
worker_1          | [nodemon] starting `node worker.js`
worker_1          | Parsing application configuration...
worker_1          | Enabling Kue GUI...
worker_1          | Enabling health checks...
worker_1          | Subscribing to job queues...
worker_1          | Worker error occurred: { [Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379]
worker_1          |   code: 'EAI_AGAIN',
worker_1          |   errno: 'EAI_AGAIN',
worker_1          |   syscall: 'getaddrinfo',
worker_1          |   hostname: 'redis',
worker_1          |   host: 'redis',
worker_1          |   port: 6379 }
```

P.S. I'll add output with `DNSMASQ_VERBOSE` shortly.

**Comment by janeczku** [comment]
Maybe related: https://github.com/docker/compose/issues/3078

What's the version of your docker engine? Looks like from 1.10 linked containers can only be looked up from Docker's embedded DNS server and they are no longer propagated to /etc/hosts.

**Comment by kop** [comment]
With `DNSMASQ_VERBOSE` enabled I got this:

```
worker_1          | level=debug msg="Received DNS query for \"redis.\" from \"127.0.0.1:58701\" with type 1" 
worker_1          | level=debug msg="Can not forward query, name too short: `redis.'"
```

**Comment by janeczku** [comment]
Aha! There should also be a line similar to this:

Ready for queries on tcp://127.0.0.1:53 - Nameservers: [10.173.45.1:53]

**Comment by kop** [comment]
Yup, it's here:

```
level=info msg="Starting go-dnsmasq server 1.0.0 ..."
level=info msg="Search domains in use: []"
level=debug msg="Found host:ip pairs in /etc/hosts:"
level=debug msg="18081b023ca4 : 172.19.0.3" 
level=debug msg="Configuring nameserver in /etc/resolv.conf" 
level=info msg="Ready for queries on tcp://127.0.0.1:53 - Nameservers: [127.0.0.11:53]"
level=info msg="Ready for queries on udp://127.0.0.1:53 - Nameservers: [127.0.0.11:53]"
```

**Comment by janeczku** [comment]
Okay that seems to be Docker's embedded DNS server. So far so good. Essentially go-dnsmasq refuses to forward single-label queries because normally the upstream server would be a public resolver. In this case it is a service discovery DNS server and single label queries should be allowed.

**Comment by janeczku** [comment]
I updated all images to go-dnsmasq v1.0.3 which allows setting the minimum number of labels a name must have in order to forward the query. The builds are currently pending in Docker Hub but once they are finished you may wanna try it out:

```
  # My app (built from alpine-kubenetes)
  worker:
    build: ./worker
    volumes:
      - ./worker:/srv/worker
    links:
      - redis
    environment:
      - DNSMASQ_NDOTS: 1
```
